# Generated by Django 2.1.5 on 2022-02-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('bitcoin', models.FloatField()),
                ('dollars', models.FloatField()),
                ('creator', models.TextField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=200)),
                ('dollars_trans', models.FloatField(default=0)),
                ('buy', models.FloatField(default=0)),
                ('sell', models.FloatField(default=0)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('ended', models.BooleanField(default=False)),
                ('good', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField(default='', max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('bitcoin', models.FloatField()),
                ('dollars', models.FloatField()),
                ('bitcoin_init', models.FloatField()),
                ('dollars_init', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
