# Generated by Django 2.1.5 on 2022-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trans_one_bit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='bc',
            field=models.FloatField(default=0),
        ),
    ]
